### PR TITLE
Warning fixes, ibmtss URL update

### PR DESCRIPTION
**Pull request by hramrach**
Old warning fixes that still apply, companion project URL update.

### CODE REVIEW

**Review by kgoldman — APPROVED** [review]

**Review by kgoldman — COMMENTED** [review]
This does not seem right.

Today: If it immediately hits the end of the list, NvNext does not change nvHandle. Then *handle is set to 0, the initial value of nvHandle.

With patch: If it skips *handle=nvHandle, so *handle is unchanged. The function comments say it should return 0.

**Review by kgoldman — COMMENTED** [review]
Thanks, fixed.

**Comment by hramrach** [comment]
The warnings are addressed in a different way already, only the doc update is still relevant.

Thanks

**Comment by hramrach** [comment]
no, the TcpServerPosix one still fails when building with older gcc versions

**Review by kgoldman — COMMENTED** [review]
I don't recall if I responded to this.  It may also be obsolete with the latest code.

If the function returns 0, end of the list, the caller should know that handle is invalid.

In the current code, *handle is set to nvHandle, which is 0. With this suggestion, it would be not be set. I don't think it matters, but perhaps 0 is better than uninitialized?

**Comment by hramrach** [comment]
uint32_t actHandle;
			  ok = ReadUINT32(s, &actHandle);
			  WriteUINT32(s, _rpc__ACT_GetSignaled(actHandle));	
			  break;
			  
It's not initialized to 0. If it were the compiler would not complain.

**Comment by hramrach** [comment]
I think this is addressed in current code now.

**Pull request closed without merging**
